### ISSUE TITLE
Before you arrive gateway link is wrong

### ISSUE THREAD

**Issue by VennilaCity** [CityofOttawa/immigration_zen#13]
Clicking on Before You Arrive gateway leads to the home page.

**Comment by minorOffense** [comment]
Should be good now.

It's set to "before-you-arrive"

If you want to change any of those links, you can set their values here: https://staging.ottawa.ca/en/admin/structure/menu/manage/menu-immigration-portal/list

**Comment by VennilaCity** [comment]
It still is loading the portal home page when clicked.

**Comment by minorOffense** [comment]
Yes it does because you don't have content posted to that URL.

You need to create content for that page.

If you want that at a different URL post it here and I'll change the link to point to it (or you can edit the menu with the links I sent yesterday).

## 

Mathew Winstone
mathew.winstone@ottawa.camailto:mathew.winstone@ottawa.ca

On 2013-10-01, at 7:43 AM, VennilaCity <notifications@github.com<mailto:notifications@github.com>> wrote:

It still is loading the portal home page when clicked.

—
Reply to this email directly or view it on GitHubhttps://github.com/CityofOttawa/immigration_zen/issues/13#issuecomment-25442410.

This e-mail originates from the City of Ottawa e-mail system. Any 
distribution, use or copying of this e-mail or the information it 
contains by other than the intended recipient(s) is unauthorized. 
If you are not the intended recipient, please notify me at the 
telephone number shown above or by return e-mail and delete 
this communication and any copy immediately. Thank you.

Le présent courriel a été expédié par le système de courriels de 
la Ville d'Ottawa. Toute distribution, utilisation ou 
reproduction du courriel ou des renseignements qui s'y trouvent 
par une personne autre que son destinataire prévu est interdite. 
Si vous avez reçu le message par erreur, veuillez m'en aviser par 
téléphone (au numéro précité) ou par courriel, puis supprimer 
sans délai la version originale de la communication ainsi que 
toutes ses copies. Je vous remercie de votre collaboration.

**Comment by VennilaCity** [comment]
There are five pages associated with it..

https://staging.ottawa.ca/en/immigration/before-you-arrive/how-to-apply-to-come-canada
https://staging.ottawa.ca/en/immigration/before-you-arrive/preparing-mentally-physically-and-financially
https://staging.ottawa.ca/en/immigration/before-you-arrive/before-you-arrive-checklist
https://staging.ottawa.ca/en/immigration/before-you-arrive/ottawa-airport
https://staging.ottawa.ca/en/immigration/before-you-arrive/what-i-wish-i-knew

**Comment by minorOffense** [comment]
I checked the taxonomy term for "before you arrive" and the url is set to "you-arrive-0" (see the bottom of the image). If you go and edit the term and set the proper path, it'll start working.

https://staging.ottawa.ca/en/taxonomy/term/3345/edit

![screen shot 2013-10-01 at 3 46 26 pm](https://f.cloud.github.com/assets/871728/1248692/5bcaff7a-2ad2-11e3-9096-bebb2fe1c50b.png)

**Comment by minorOffense** [comment]
Fixed it. It lives on "you-arrive" for now. "before-you-arrive" is in use elsewhere or has a stray entry we need to kill.
