### ISSUE TITLE
French page headings styling off

### ISSUE THREAD

**Issue by VennilaCity** [CityofOttawa/immigration_zen#30]
French page headings(h1, h2 etc) do not seem to pick up the page color styling.

**Comment by tiffanytse** [comment]
Before I fix this, please fix the url of the page (because that's what they styling will be dependent on and it will break if we change the url later. Not sure why it has a 0 at the end )

http://staging.ottawa.ca/fr/immigration/pourquoi-choisir-ottawa-0

@VennilaCity Let me know when you do. :)

**Comment by VennilaCity** [comment]
If I remove the 0, then the gateway link just goes to this page https://staging.ottawa.ca/fr/immigration/etudiants-etrangers/pourquoi-choisir-ottawa not sure why...maybe something todo with the permalink?

**Comment by tiffanytse** [comment]
It must have been the order in which the pages/content was created, since that page/node was created first and it has the exact same title drupal puts a 0 at the end to distinguish it. it's probably best to go and change the url of the inside page to have the 0, so that the top level navigation has nice urls. Perhaps Mat has some insight? @minorOffense @VennilaCity

**Comment by VennilaCity** [comment]
The URLs are corrected now.

**Comment by tiffanytse** [comment]
Thanks :)

**Comment by tiffanytse** [comment]
Should be fixed now
