### ISSUE TITLE
Look and Feel in IE is off

### ISSUE THREAD

**Issue by VennilaCity** [CityofOttawa/immigration_zen#8]
The entire portal look and feel is completely different in IE

**Comment by AaronByrne** [comment]
needs to be fixed before launch but for review please instruct client to use Chrome.
@minorOffense @VennilaCity

**Comment by minorOffense** [comment]
Right, so this is a "duh" moment for me. In order for IE8 to work with media queries we use Respond.js and Selectivizr.js libraries. These only work in IE8 when "@import" statements aren't used to include css. When Drupal is in dev mode, we disable the CSS aggregator which then causes all stylesheets to be included individually with @import commands.

By going to admin/config/development/performance and enabling the "css aggregator" the page now renders fine in IE8 (safe for one issue with widths on the boxes but I'm working on it).

This also explains why it looked fine on my local VM when I was testing IE8...

@elcazador

**Comment by tiffanytse** [comment]
Page has been tested/fixed for ie8 :) @VennilaCity @elcazador @minorOffense

**Comment by VennilaCity** [comment]
The gateway blocks with images on the homepage not displaying in IE. The top navigation menu missing the colors.

The webpage layout looks like a mobile view.

@minorOffense @elcazador

**Comment by webstandards** [comment]
Screenshot of IE 8, pretty unusable, flips to mobile view no matter what size and navigation blocks are blank.
IE 10 and 11 however work quite well at all responsive widths, only issue seems to be alignment of text overlays on the two left navigation blocks.

IE8
![immigration_ie8](https://f.cloud.github.com/assets/4095270/1410146/9d5851e2-3d9f-11e3-8490-5de0c834f173.jpg)

IE10/11
![immigration_ie11](https://f.cloud.github.com/assets/4095270/1410150/a7190be0-3d9f-11e3-9589-4d0b4807b4c9.jpg)

**Comment by AaronByrne** [comment]
the IE fixes seem to have been reverted we need them reinstated

**Comment by minorOffense** [comment]
When we disable the css aggregator that's what happens. The polyfill for IE and the media queries only work with css aggregation enabled.

**Comment by webstandards** [comment]
Much better in IE8, however carousel items are unreadable because there's nothing behind the text, and as noted before the alignment of text overlays on navigation blocks is off in IE8,10,11. See screenshot.
![ie8_problems](https://f.cloud.github.com/assets/4095270/1419970/620bacb2-3fd7-11e3-9d25-bdf35bc95a10.jpg)

**Comment by tiffanytse** [comment]
I will have to change the font sizing to fix this issue, and but a break in the first text overlay; because the content has changed, and this is causing the issue. The wrapping of working/doing business to a second line is making it higher than the others; and same with 'why choose ottawa' the description text is now only a single line, whereas all the others are two. @webstandards

**Comment by minorOffense** [comment]
Duplicate issue #41

**Comment by webstandards** [comment]
@minorOffense "alignment of text overlays on navigation blocks is off in IE8,10,11" is not a duplicate issue.

**Comment by minorOffense** [comment]
Yes it is, please don't reopen the issue. I'm opening one for that specifically as I just talked to @AaronByrne about it.
